version: '3.0'

services:
  nginx:
    image: nginx:latest
    ports:
      - "150:120"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
    container_name: server
  php:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "7000:9000"
    container_name: project
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - ./tmp/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    container_name: phpmyadmin
